//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleProgPoe
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaptureModule
    {
        public int Id { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ModuleName { get; set; }
        public string ModuleCode { get; set; }
        public Nullable<int> ModuleClassHrs { get; set; }
        public Nullable<int> ModuleCredits { get; set; }
        public Nullable<int> SemWeeks { get; set; }
        public string SemDate { get; set; }
        public Nullable<int> SelfStudyHour { get; set; }
    
        public virtual user user { get; set; }
    }
}
